# Параметры из my.telegram.org
api_id = 123456789
api_hash = '**********'

# Бот из @BotFather
bot_token = '****************'

# id канала куда будут сливаться все новости
kgh_chat_id = -1001561131709

# Ссылки на телеграмм каналы
telegram_channels = {
    1354034423: 'https://t.me/rusmsk',
    1003313758: 'https://t.me/moscowmap',
    1597228121: 'https://t.me/DGONews',
    1387151456: 'https://t.me/kgh_moscow',
    1393945742: 'https://t.me/moslentaru',
    1135758880: 'https://t.me/mchs_moscow_operational',
    1588259750: 'https://t.me/testchanel021122',
    1117628569: 'https://t.me/breakingmash',
    1064785472: 'https://t.me/mosrutop',
    1643894529: 'https://t.me/mchsmsk',
    1497406484: 'https://t.me/vmoskva',
    1135115323: 'https://t.me/moscownewsagency',
    1001104273: 'https://t.me/lifenews',
    1332155048: 'https://t.me/mosoati',
    1405834839: 'https://t.me/mginews',
    1182713589: 'https://t.me/mosecomonitoring',
    1414148197: 'https://t.me/liftroskin'
    }

# Ссылки на RSS каналы
rss_channels = {
    'www.moscow.mchs.gov.ru': 'https://moscow.mchs.gov.ru/deyatelnost/press-centr/operativnaya-informaciya/rss',
    'www.moslenta.ru': 'https://moslenta.ru/exports/rss.xml',
    'www.112.mos.ru': 'https://112.mos.ru/rssexport/',
    'www.news.rambler.ru': 'https://news.rambler.ru/rss/moscow_city/',
    'www.ria.ru': 'https://ria.ru/export/rss2/archive/index.xml',
    'www.aif.ru': 'https://aif.ru/rss/all.php',
    'www.mos.ru': 'https://www.mos.ru/rss',
    'www.dom-i-dvor.info': 'https://www.dom-i-dvor.info/news/rss',
    'www.mskagency.ru': 'https://www.mskagency.ru/rss/index.rss',
    'www.iz.ru': 'https://iz.ru/xml/rss/all.xml',
    'www.uzao.mos.ru': 'https://uzao.mos.ru/rssexport/',
    'www.uao.mos.ru': 'https://uao.mos.ru/rssexport/',
    'www.uvao.mos.ru': 'https://uvao.mos.ru/rssexport/',
    'www.szao.mos.ru': 'https://szao.mos.ru/rssexport/',
    'www.sao.mos.ru': 'https://sao.mos.ru/rssexport/',
    'www.svao.mos.ru': 'https://svao.mos.ru/rssexport/',
    'www.zao.mos.ru': 'https://zao.mos.ru/rssexport/',
    'www.vao.mos.ru': 'https://vao.mos.ru/rssexport/',
    'www.cao.mos.ru': 'https://cao.mos.ru/rssexport/',
    'www.zelao.mos.ru': 'https://zelao.mos.ru/rssexport/',
    'www.tinao.mos.ru': 'https://tinao.mos.ru/rssexport/',
    'www.bogorodskoe.mos.ru': 'https://bogorodskoe.mos.ru/rssexport/',
    'www.exp.mos.ru': 'https://exp.mos.ru/rssexport/',
    'www.gorod.mos.ru': 'https://gorod.mos.ru/?show=news&action=rss',
    #'': '',
    #'': '',
   # '': '',
   # '': '',
   # '': '',
   # '': '',
   # '': '',
   # '': '',
   # '': '',
    #'': '',
    #'': '',
    #'': '',
    }

# Фильтр ключевых слов новостей
key_words = {
    'погиб',
    'превыш',
    'зафикс',
    'жалоб',
    'повреж',
    'повред',
    'повален',
    'ликвиди',
    'локализ',
    'операти',
    'контро',
    'предупр',
    'экстрен',
    'техног',
    'ситуацио',
    'задымл',
    'экомони',
    'чп',
    'чрезвыч',
    'несчаст',
    'перекры',
    'движен',
    'шторм',
    'голол',
    'опасн',
    'порыв',
    'авари',
    'пострад',
    'лифт',
    'происше',
    'жкх',
    'снег',
    'снеж',
    'возгоран',
    'ресурсосн'
    'отключ',
    'пожар',
    'взрыв',
    'взорв',
    'хлопок',
    'вандал',
    'возгор',
    'восплам'
    'гидромет',
    'кгх',
    'бирюков',
    'неблагопр',
    'мчс',
    'шквалис',
    'теплосн',
    'теплотр',
    'отопит',
    'водосн',
    'электросна',
    'цтп',
    'итп',
    'тэц',
    'кнс',
    'канализ',
    'хвс',
    'гвс',
    'дтп',
    'тревог',
    'насра'
    'обосс',
    'обоср',
    'насрат',
    'ссал',
    'осрал',
    'осрат',
    'бомж',
    'разруш',
    'разрух',
    'обруш',
    'выбоин',
    'трещин',
    'протек',
    'стояк',
    'мусор',
    'свалк',
    'тко',
    'отход',
    'трагед',
    'коммунал',
}
